name: asset bundles validation
on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]  


env:
  secret: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
  DATABRICKS_CLIENT_ID: c767c4f4-8603-488e-bdfd-d3c436f2e49e # ${{ DATABRICKS_CLIENT_ID }}
  host: https://adb-984752964297111.11.azuredatabricks.net/ # ${{ DATABRICKS_HOST }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - name: setup databrickscfg
      run: |
        cat <<EOF > ~/.databrickscfg
        [devEnv]
        host          = $host
        client_id     = $DATABRICKS_CLIENT_ID
        client_secret = $secret
        EOF

    - name: Install dependencies
      run: |
        curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh;
        databricks -v;
        cat ~/.databrickscfg
        
        databricks clusters list -p devEnv
        
