name: asset bundles validation
on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - name: Install dependencies
      run: |
        curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh;
        databricks -v;
        # databricks auth login --host <AZURE_DATABRICKS_HOST>;
        databricks bundle init;
        
