name: asset bundles validation
on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]  


env:
  DATABRICKS_CLIENT_SECRET: ${{ AZURE_DATABRICKS.DATABRICKS_CLIENT_SECRET }}
  DATABRICKS_CLIENT_ID: ${{ AZURE_DATABRICKS.DATABRICKS_CLIENT_ID }}
  DATABRICKS_HOST: ${{ AZURE_DATABRICKS.DATABRICKS_HOST }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - name: Install dependencies
      run: |
        curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh;
        databricks -v;
        databricks auth login;
        databricks bundle init;
        
