name: asset bundles validation
on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
env:
  DATABRICKS_HOST: https://adb-3093429238214168.8.azuredatabricks.net
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - name: Install dependencies
      run: |
        curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
        databricks -v  # print out the version of databricks cli
        databricks auth login --host <AZURE_DATABRICKS_HOST>  # log into workspace
        databricks bundle validate
        
